sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 86 87 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 87 88 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 88 89 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 92 91 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 91 90 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 92 93 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 93 94 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 94 95 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 98 97 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 97 96 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 98 99 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 99 100 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 100 101 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 104 103 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 103 102 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 104 105 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 105 106 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 106 107 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 110 109 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 109 108 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 110 111 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 111 112 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 112 113 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 116 115 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 115 114 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 116 117 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 117 118 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 118 119 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 122 121 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 121 120 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 122 123 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 123 124 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 124 125 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 128 127 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 127 126 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 128 129 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 129 130 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 130 131 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 134 133 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 133 132 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 134 135 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 135 136 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 136 137 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 140 139 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 139 138 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 140 141 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 141 142 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 142 143 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 146 145 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 145 144 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 146 147 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 147 148 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 148 149 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 152 151 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 151 150 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 152 153 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 153 154 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 154 155 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 158 157 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 157 156 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 158 159 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 159 160 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 160 161 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 164 163 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 163 162 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 164 165 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 165 166 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 166 167 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 170 169 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 169 168 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 170 171 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 171 172 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 172 173 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 176 175 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 175 174 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 176 177 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 177 178 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 178 179 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 182 181 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 181 180 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 182 183 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 183 184 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 184 185 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 188 187 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 187 186 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 188 189 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 189 190 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 190 191 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 194 193 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 193 192 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 194 195 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 195 196 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 196 197 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 200 199 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 199 198 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 200 201 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 201 202 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 202 203 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 206 205 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 205 204 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 206 207 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 207 208 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 208 209 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 212 211 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 211 210 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 212 213 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 213 214 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 214 215 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 218 217 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 217 216 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 218 219 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 219 220 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 220 221 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 224 223 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 223 222 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 224 225 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 225 226 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 226 227 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 230 229 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 229 228 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 230 231 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 231 232 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 232 233 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 236 235 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 235 234 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 236 237 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 237 238 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 238 239 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 242 241 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 241 240 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 242 243 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 243 244 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 244 245 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 248 247 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 247 246 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 248 249 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 249 250 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 250 251 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 254 253 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 253 252 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 254 255 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 255 256 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 256 257 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 260 259 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 259 258 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 260 261 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 261 262 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 262 263 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 266 265 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 265 264 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 266 267 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 267 268 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 268 269 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 272 271 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 271 270 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 272 273 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 273 274 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 274 275 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 278 277 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 277 276 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 278 279 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 279 280 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 280 281 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 284 283 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 283 282 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 284 285 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 285 286 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 286 287 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 290 289 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 289 288 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 290 291 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 291 292 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 292 293 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 296 295 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 295 294 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 296 297 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 297 298 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 298 299 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 302 301 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 301 300 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 302 303 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 303 304 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 304 305 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 308 307 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 307 306 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 308 309 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 309 310 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 310 311 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 314 313 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 313 312 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 314 315 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 315 316 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 316 317 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 320 319 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 319 318 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 320 321 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 321 322 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 322 323 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 326 325 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 325 324 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 326 327 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 327 328 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 328 329 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 332 331 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 331 330 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 332 333 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 333 334 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 334 335 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 338 337 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 337 336 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 338 339 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 339 340 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 340 341 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 344 343 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 343 342 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 344 345 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 345 346 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 346 347 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 350 349 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 349 348 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 350 351 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 351 352 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 352 353 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 356 355 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 355 354 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 356 357 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 357 358 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 358 359 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 362 361 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 361 360 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 362 363 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 363 364 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 364 365 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 368 367 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 367 366 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 368 369 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 369 370 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 370 371 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 374 373 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 373 372 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 374 375 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 375 376 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 376 377 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 380 379 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 379 378 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 380 381 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 381 382 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 382 383 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 386 385 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 385 384 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 386 387 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 387 388 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 388 389 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 392 391 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 391 390 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 392 393 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 393 394 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 394 395 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 398 397 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 397 396 2
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 398 399 3
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 399 400 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 400 401 4
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 404 403 1
sh warpintsectionimage.sh /nobackup/scicompsoft/yuTest/markCembrowski/wholeBrain1404978drd2Rabies/workdir/red /groups/jacs/jacsShare/yuTest/Share4Mark/AMBA/resliced/LinearTransforms 403 402 2
